# Generated by Django 4.2.13 on 2024-06-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0002_mailbox_delete_deals'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='bcc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='cc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='flags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='in_reply_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='mailUsername',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='messageId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='references',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='reply_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='to_mails',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='uid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='attachements',
            field=models.ImageField(blank=True, null=True, upload_to='emailAttachments'),
        ),
    ]
