# Generated by Django 4.2.13 on 2024-06-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0003_mailbox_bcc_mailbox_cc_mailbox_flags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
