# Generated by Django 4.2.13 on 2024-06-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0004_mailbox_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbox',
            name='html',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
