# Generated by Django 4.2.13 on 2024-06-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0005_alter_mailbox_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='aasignedTo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='channel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='priority',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
