# Generated by Django 4.2.13 on 2024-06-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0006_mailbox_aasignedto_mailbox_channel_mailbox_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbox',
            name='aasignedTo',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='channel',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='priority',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
