# Generated by Django 4.2.13 on 2024-06-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0008_sentbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='draftBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=100, null=True)),
                ('mailUsername', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('fromMail', models.CharField(blank=True, max_length=100, null=True)),
                ('to_mails', models.JSONField(blank=True, default=list, null=True)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.CharField(blank=True, max_length=100, null=True)),
                ('html', models.CharField(blank=True, max_length=100, null=True)),
                ('flags', models.JSONField(blank=True, default=list, null=True)),
                ('cc', models.CharField(blank=True, max_length=100, null=True)),
                ('bcc', models.CharField(blank=True, max_length=100, null=True)),
                ('reply_to', models.CharField(blank=True, max_length=100, null=True)),
                ('messageId', models.CharField(blank=True, max_length=100, null=True)),
                ('attachements', models.ImageField(blank=True, null=True, upload_to='emailAttachments')),
                ('in_reply_to', models.CharField(blank=True, max_length=100, null=True)),
                ('references', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='open', max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('aasignedTo', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('channel', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('priority', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
    ]
