# Generated by Django 4.2.13 on 2024-07-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0009_draftbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbox',
            name='attachements',
            field=models.FileField(blank=True, null=True, upload_to='emailAttachments'),
        ),
    ]
