# Generated by Django 4.2.13 on 2024-07-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0013_sentbox_attachments_remove_sentbox_attachements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='headers',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
