# Generated by Django 4.2.13 on 2024-07-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0018_channel_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
