# Generated by Django 4.2.13 on 2024-07-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0019_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='createdBy',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
