# Generated by Django 4.2.13 on 2024-07-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0021_alter_mailbox_cc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbox',
            name='aasignedTo',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='bcc',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='channel',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
