# Generated by Django 4.2.13 on 2024-07-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0022_alter_mailbox_aasignedto_alter_mailbox_bcc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentbox',
            name='aasignedTo',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='sentbox',
            name='bcc',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='sentbox',
            name='cc',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
