# Generated by Django 4.2.13 on 2024-07-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0024_alter_draftbox_aasignedto_alter_draftbox_bcc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='mailboxBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
