# Generated by Django 4.2.13 on 2024-07-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0026_rename_aasignedto_draftbox_assignedto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailbox',
            name='assignedTo',
        ),
        migrations.AddField(
            model_name='mailbox',
            name='assignedTo',
            field=models.ManyToManyField(blank=True, to='emailapp.profile'),
        ),
    ]
