# Generated by Django 4.2.13 on 2024-07-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0027_remove_mailbox_assignedto_mailbox_assignedto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftbox',
            name='assignedTo',
        ),
        migrations.RemoveField(
            model_name='sentbox',
            name='assignedTo',
        ),
        migrations.AddField(
            model_name='draftbox',
            name='assignedTo',
            field=models.ManyToManyField(blank=True, to='emailapp.profile'),
        ),
        migrations.AddField(
            model_name='sentbox',
            name='assignedTo',
            field=models.ManyToManyField(blank=True, to='emailapp.profile'),
        ),
    ]
